### ISSUE TITLE
Application icon in Flatseal is broken or missing but works in icon only task manager and launcher

### ISSUE THREAD

**Issue by ghtesting2020** [flathub/org.kde.filelight#31]
Filelight 23.08.4 flatpak.

When in flatseal out of all applications in the Applications sidebar only Filelight displays a white icon with a grey exclamation point in a triangle indicating either missing or broken icon. None of other KDE apps like Kalk or Dolphin do this only Filelight.

**Comment by bbhtt** [comment]
This should be fixed by https://github.com/flathub/org.kde.filelight/pull/32

**Comment by travier** [comment]
This should be fixed now.
