### ISSUE TITLE
Consider moving to stable

### ISSUE THREAD

**Issue by travier** [flathub/org.kde.filelight#8]
Now that https://bugs.kde.org/show_bug.cgi?id=450835 has been fixed, we might consider moving this one to stable.

**Comment by thibaultmol** [comment]
Is this holding back from it being published to Flathub? Because not having Filelight on Flathub is one of the things that's holding me back from using Fedora Kinoite

**Comment by travier** [comment]
You can install it from the beta remote, it's currently the exact same code that you will get once we move that to stable.

@tsdgeos @Pointedstick How do you feel about moving this one to stable?

**Comment by Pointedstick** [comment]
+1 from me; the intention was always to move this to stable with the 22.08 release.

**Comment by travier** [comment]
OK, let's wait for 22.08 then.

**Comment by travier** [comment]
I've tested the new release and it looks great!

**Comment by travier** [comment]
I've pushed a master branch but I don't have power to make it the default / trigger the automation.

Maybe @nedrichards @hfiguiere @barthalion ?

**Comment by hfiguiere** [comment]
Nothing to do for the build, it's automatic. And it's there: 
https://buildbot.flathub.org/#/builders/32/builds/106447

Allow a few hours for publishing, albeit you shoud have permission to press publish.

The rest, I can't help, sorry (not enough privileges)

**Comment by travier** [comment]
Thanks. Where should I find the button to press publish?

**Comment by hfiguiere** [comment]
> https://buildbot.flathub.org/#/builders/32/builds/106447

But you need to login with your github account.

**Comment by hfiguiere** [comment]
but it will happen by itself otherwise after 4 hoursl

**Comment by travier** [comment]
Thanks

**Comment by travier** [comment]
We have it in stable now. Keeping this one open waiting for an admin to remove the beta branch and make master the default.

**Comment by travier** [comment]
Ping @nedrichards @barthalion @ebassi : We need to make master the main branch for this repo please (and remove the beta branch). Thanks!

**Comment by barthalion** [comment]
I changed the default branch to master. I will keep beta as-is, we usually don't remove it.

**Comment by travier** [comment]
Thanks!
